### PR TITLE
Solve warnings

### PR DESCRIPTION
**Pull request by Ahmed-Aladdiin**
In this Pull Request, I fixed some of the code errors and some code pieces that are prone to error:
- Delete statement can't work on multiple pointers simultaneously; each pointer must be deleted in its own statement
- Error messages were written in a mixture of C print and C++ std::cerr. Rewrote it in a proper syntax
- Didn't specify all 4 attributes of color which could lead to unexpected behavior
- Created a util function to compare const char* with strings, as direct comparison using the == operator is not favorable; and it seems that you don't want to include external libraries like <string> or <cstring>, so I implemented the function my self

### CODE REVIEW

**Review by tamtaasatiani — COMMENTED** [review]
Is [9b1436a](https://github.com/tamtaasatiani/tahmlib/pull/24/commits/9b1436ad9241062655631f8f6c4dfad0e81fc519) necessary? I don't want to use std::endl for every line since it also flushes, which is rather costly. I'd like to use \n instead std::endl wherever possible

**Comment by Ahmed-Aladdiin** [comment]
No problem, this can be easily solved by exchanging std::endl with '\n'. Give me a minute.

**Comment by tamtaasatiani** [comment]
I also don't quite get [68c0f2e](https://github.com/tamtaasatiani/tahmlib/pull/24/commits/68c0f2e1f216b7ad80453ca6fadc717a6cad8d8d), aren't string and const char pointers the same? Especially since the commit uses const char pointers anyway? Or is the whole point of this function that it converts one of these two (which was previously a string) into a const char pointer?

**Comment by Ahmed-Aladdiin** [comment]
comparing a 'const char*' with a 'string' (ex: if (alignment == "center")) does actually compare between the address of two pointers and not the content of them, so we should use the strcmp function from the <string> library to compare the contents of the two variable. (that is how things are supposedly work under the hood)
You can refer to this question on StackOverflow
https://stackoverflow.com/questions/22572987/why-use-strcmp-instead-of-in-c#:~:text=strcmp%20compares%20the%20actual%20C,point%20to%20the%20same%20position.

and since you don't want to import the <string> library and keep things minimal, I created a function dedicated to do so.

**Comment by Ahmed-Aladdiin** [comment]
If you were using a 'std::string' variable type instead of a 'const char*' it would have been ok, but since you are using a 'const char*' it is better to use a dedicated function, either strcmp or you make your own function.

**Comment by tamtaasatiani** [comment]
std::string?? In the tahmlib repository?? Are you sure? I'm pretty sure I only used it in pong++

**Comment by tamtaasatiani** [comment]
Could the custom function be changed with operator overloading in the future? Or is operator overloading only for custom types? Basically, so that alignment == "center" yields the desired result?

**Comment by Ahmed-Aladdiin** [comment]
Yes, it can be overloaded.

**Pull request merged**
