### PR TITLE
Tiny enhancement (singletone + errors logging)

### PR DESCRIPTION
**Pull request by dmfv**
Hello Tamta
I found your video on YouTube about this project and followed the link to check it.
I saw a few issues so I tried to resolve them :)

### CODE REVIEW

**Review by tamtaasatiani — CHANGES_REQUESTED** [review]
tahm instance can't be private and hidden behind a getinstance method because it needs to be accessed directly by the user. (the other commit is great but i'm not sure how to merge only one of the commits lol)

**Comment by dmfv** [comment]
Why is the getInstance method a bad option for this case?
Anyway I updated the code according to this idea

You always could cherry-pick commit from the branch :)

**Comment by tamtaasatiani** [comment]
Did some changes to make the code consistent with the engine in general, will test and merge tomorrow

**Comment by dmfv** [comment]
okay, that's reasonable.
Don't know the motivation to do not use smart pointers but I agree that the code should be consistent
Btw you still need to define static class members otherwise you don't have the complete type.

You could also consider switching to C++17 to use inline keywords with static members.

https://en.cppreference.com/w/cpp/language/static
https://godbolt.org/z/Gv1Ws8ha3

**Pull request merged**
