### PR TITLE
Main loop now runs inside "Tham" singleton.

### PR DESCRIPTION
**Pull request by Javier-Lozano**
Solved issue #5, main loop now runs inside "Tham" singleton.
I also added a Makefile to compile the current project on Linux (tested Debian 12), it's not intrusive and it can be deleted when a build systems is chosen.

### CODE REVIEW

**Review by tamtaasatiani — CHANGES_REQUESTED** [review]
"tahm" should not be coupled to "engine.h"!

**Comment by Javier-Lozano** [comment]
Got a solution. We could create callbacks by using std::function from <functional>, we create member objects

At tahm.h
```
Tahm {
...
   std::function <void()> callbackStart;
   std::function <void()> callbackUpdate;
   std::function <void()> callbackDraw;
   std::function <void(Event)> callbackKeypressed;
...
};
```
At engine.cpp

```
int main()
{
   tahm.callbackStart = start;
   tahm.callbackUpdate = update;
   tahm.callbackDraw = draw;
   tahm.callbackKeypressed = keypressed;
   ...
}
```

**Comment by Javier-Lozano** [comment]
Got a solution. We could create callbacks by using std::function from \<functional>, we create member objects

At tahm.h
```
Tahm {
...
   std::function <void()> callbackStart;
   std::function <void()> callbackUpdate;
   std::function <void()> callbackDraw;
   std::function <void(Event)> callbackKeypressed;
...
};
```
At engine.cpp

```
int main()
{
   tahm.callbackStart = start;
   tahm.callbackUpdate = update;
   tahm.callbackDraw = draw;
   tahm.callbackKeypressed = keypressed;
   ...
}
```

**Comment by Javier-Lozano** [comment]
I should've addressed issue #1 and #5 together beforehand. Since this branch fell behind recent changes I decided to close the request, I still think I can address those issues but I'll wait for a response before sending a request, sorry for the inconveniences :sweat_smile:

**Comment by tamtaasatiani** [comment]
no-no! i'm sorry for your inconvenience and thank you for participating either way!
that being sad, if you do plan on contributing, could you use plain function pointers instead of std function? i plan on using the standard library as minimally as possible for now

**Comment by Javier-Lozano** [comment]
Got it working! :thinking:

tahm.h
```c++
typedef void (*vFunc)();
typedef void (*vFuncEv)(Event);

class Tahm {
...
private:
    void handleEvents();
    vFunc callbackUpdate;
    vFunc callbackDraw;
    vFuncEv callbackKeypressed;
public:
    void init(vFunc start, vFunc update, vFunc draw, vFuncEv keypressed);
    void run();
...
};
```
tahm.cpp
```c++
void Tahm::init(vFunc start, vFunc update, vFunc draw, vFuncEv keypressed)
{
    callbackUpdate = update;
    callbackDraw = draw;
    callbackKeypressed = keypressed;
    
    start(); // Call Start right away
    window->init();
    renderer->init();
    audio->setupDevice();
}

void Tahm::run()
{
	while(running)
	{
		// Update
		handleEvents();
		callbackUpdate();
		//Draw
		renderer->prepare();
		callbackDraw();
		renderer->present();
		
		SDL_Delay(16);
	}
}

void Tahm::handleEvents()
{
	Event event;
	while (SDL_PollEvent(&event))
	{
		switch (event.type)
		{
		case SDL_QUIT:
			running = false;
			break;
		case SDL_KEYDOWN:
			callbackKeypressed(event);
			break;
		default:
			break;
		}
	}
}
```
engine.cpp
```c++
int main(int argc, char* argv[])
{
	tahm.init(start, update, draw, keypressed);
	tahm.run();
	tahm.destroy();

	return 0;
}
```

Now the main loop runs inside Tahm class with callbacks.

**Pull request closed without merging**
